name: Test Suite
permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate JavaScript syntax
        run: |
          node -c game.js
          node -c sentences.js  
          node -c translations.js
          echo "JavaScript syntax validation passed"

      - name: Run custom test suite
        run: npm test

      - name: Start static server
        run: |
          npm start &
          sleep 5
          echo "Static server started"

      - name: Test server response
        run: |
          curl -f http://localhost:3000/ || exit 1
          curl -f http://localhost:3000/test.html || exit 1
          echo "Server tests passed"

      - name: Install browser testing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          
      - name: Run browser tests
        run: |
          # Simple smoke test - check if page loads without errors
          timeout 30s bash -c 'until curl -s http://localhost:3000/ > /dev/null; do sleep 1; done'
          echo "Browser tests passed"